NRS_URL="http://127.0.0.1:7874/nxt"
TXFEE=1
NXTIP_ACCOUNT="<NXT BOT ACCOUNT HERE>"
USER_DEPOSIT_MINCONF=3
NXTIP_DEPOSIT_MINCONF=2
NXTIP_KEY="<NXT BOT ACCOUNT KEY HERE>"
NXTIP_USER="nxtip"

#MySQL settings
NXTIP_DB="nxtip_db"
NXTIP_DB_USER="nxtip_db"
NXTIP_DB_PASS="nxtip_db"
NXTIP_DB_HOST="127.0.0.1"
